# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

CRATES="
"

RUST_MIN_VER="1.93"

inherit cargo gnome.org gnome2 meson xdg

DESCRIPTION="View images"
HOMEPAGE="https://apps.gnome.org/Loupe"

# SRC_URI for loupe is set by gnome.org eclass.
SRC_URI+="
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://binhost.h97i.org/Crates/loupe-51.0.0-crates.tar.xz
	"
fi


LICENSE="GPL-3+"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD ISC MIT Unicode-3.0
	|| ( LGPL-2.1+ MPL-2.0 )
"
SLOT="0"
KEYWORDS="~amd64"

IUSE="X heif gif jpeg jpegxl svg tiff wayland"

BDEPEND="
	dev-util/itstool
	virtual/pkgconfig
"
# sys-crates in pycargoebuild order
DEPEND="
	x11-libs/cairo[X?]
	media-libs/glycin-loaders
	dev-libs/glib:2
	sys-devel/gettext
	media-libs/graphene
	x11-libs/pango[X?]
	media-libs/fontconfig
"
# meson.build file
DEPEND+="
	>=gui-libs/gtk-4.16.0:4[X?,wayland?]
	>=gui-libs/libadwaita-1.7.0:1
	>=dev-libs/libgweather-4.0.0:4=
	>=media-libs/lcms-2.12.0:2[jpeg?,tiff?]
	>=sys-libs/libseccomp-2.5.0
"
RDEPEND="${DEPEND}
	media-libs/glycin-loaders:2=[heif?,jpegxl?,svg?]
"

QA_FLAGS_IGNORED="usr/bin/loupe"

src_configure() {
	local emesonargs=(
		$(meson_feature X x11)
	)
	meson_src_configure
	ln -s "${CARGO_HOME}" "${BUILD_DIR}/cargo-home" || die
}

pkg_preinst() {
	xdg_pkg_preinst
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
