
games-util/game-device-udev-rules
sys-libs/libudev-compat
gui-wm/gamescope
media-libs/vkroots
dev-libs/wayland-protocols
dev-libs/libei
dev-libs/wayland
dev-util/wayland-scanner

=media-libs/mesa-26.0*
net-libs/msgraph

dev-python/fastapi

net-misc/sunshine
media-libs/nv-codec-headers
net-misc/moonlight
