app-crypt/certbot certbot-nginx
app-misc/mime-types nginx
sys-apps/systemd boot cryptsetup ukify
app-arch/unzip natspec
app-crypt/gnupg usb
app-text/xmlto text
net-libs/ngtcp2 gnutls
sys-libs/zlib minizip
sys-kernel/installkernel dracut systemd-boot uki ukify

sys-apps/kmod pkcs7
sys-firmware/intel-microcode hostonly
sys-apps/systemd abi_x86_32 lzma
dev-libs/icu abi_x86_32
virtual/libcrypt abi_x86_32
virtual/libintl abi_x86_32
app-arch/bzip2 abi_x86_32
sys-apps/util-linux abi_x86_32
dev-libs/libpcre2 abi_x86_32
sys-libs/gdbm abi_x86_32
sys-libs/readline abi_x86_32
dev-libs/elfutils abi_x86_32
dev-libs/glib abi_x86_32
dev-libs/expat abi_x86_32
sys-apps/lm-sensors abi_x86_32
sys-libs/readline abi_x86_32
virtual/libiconv abi_x86_32
sys-libs/pam abi_x86_32

sys-kernel/linux-firmware dist-kernel -initramfs compress-zstd savedconfig
sys-kernel/gentoo-kernel -debug -secureboot
sys-apps/dbus -X abi_x86_32
sys-apps/iproute2 -iptables
sys-fs/btrfs-progs -man
app-admin/sudo -sendmail
sys-process/psmisc X
sys-apps/groff -X
dev-vcs/git -keyring
dev-python/pillow -avif -jpeg2k -lcms -tiff -truetype -webp -xcb
app-crypt/pinentry -X -keyring -wayland
app-admin/logrotate -cron

www-servers/nginx nginx_modules_http_realip nginx_modules_http_stub_status nginx_modules_http_auth_request nginx_modules_stream_ssl_preread
www-apps/nextcloud -sqlite redis mysql -postgres
dev-lang/php -sqlite pdo ctype curl gd iconv json filter xml zlib zip opcache intl pcntl unicode xmlwriter xmlreader avif jpeg mysql mysqli png spell truetype webp exif gmp sodium sysvipc
media-gfx/imagemagick -X -openmp heif jpeg png webp svg jpegxl tiff truetype fontconfig xml zlib zip bzip2 lzma lcms pango
media-libs/libheif aom dav1d de265 gdk-pixbuf jpeg jpeg2k kvazaar threads webp x264 x265
media-libs/freetype -X harfbuzz
media-libs/gd avif fontconfig tiff truetype webp
dev-libs/libzip lzma
media-libs/lcms jpeg tiff
media-libs/tiff jpeg lzma -opengl webp
media-fonts/urw-fonts X
media-libs/glycin -gtk -vala
media-libs/glycin-loaders jpegxl svg
media-libs/libjxl gif jpeg
sys-process/audit ABI_X86: 32
app-arch/libarchive lz4
dev-libs/lzo ABI_X86: 32
media-fonts/liberation-fonts X
media-libs/libavif dav1d gdk-pixbuf
media-libs/libde265 sdl
dev-libs/libgudev introspection
x11-libs/gdk-pixbuf jpegxl
app-admin/cockpit -networkmanager
