app-admin/conky bundled-toluapp iostats lua-rsvg truetype
app-admin/logrotate -cron
app-admin/sudo -sendmail
app-crypt/certbot certbot-nginx
app-crypt/gcr gtk
app-crypt/pinentry -gtk
app-misc/mime-types nginx
app-office/libreoffice -bluetooth -mariadb -gtk4 pdfimport -mariadb
app-text/mupdf -X
app-text/papers -comics
dev-libs/libdbusmenu -gtk gtk3
games-util/steam-launcher vulkan
gnome-base/gdm -X
gnome-base/gnome -classic -extras
gnome-base/gnome-control-center -X
gnome-base/gvfs onedrive
gnome-base/nautilus -previewer
gnome-extra/evolution-data-server -oauth-gtk3
gnome-extra/gnome-software -firmware
gui-libs/gtk -vulkan
media-fonts/fonts-meta -latin
media-fonts/noto -extra
media-gfx/fontforge -gtk -X
media-libs/freetype utils
media-libs/glycin vala
media-libs/libcamera -sdl
media-plugins/gst-plugins-meta ffmpeg taglib
media-video/pipewire bluetooth extra -ffmpeg libcamera modemmanager pipewire-alsa sound-server
net-libs/gnome-online-accounts ms365
net-libs/ngtcp2 gnutls
net-libs/nodejs npm
net-misc/networkmanager -ppp -wext -concheck
net-print/cups -X -acl  -pam -systemd -usb -dbus
net-print/cups-filters -foomatic
net-print/cups-meta -foomatic
sys-apps/kmod pkcs7
sys-apps/systemd boot cryptsetup
sys-auth/polkit -gtk
sys-devel/gcc lto
sys-firmware/intel-microcode hostonly
sys-kernel/gentoo-kernel -debug -secureboot
sys-kernel/installkernel systemd-boot uki dracut
sys-kernel/linux-firmware compress-zstd -initramfs savedconfig
sys-libs/ncurses -gpm
sys-libs/zlib minizip
www-client/chromium -vaapi -hangouts -screencast
x11-drivers/nvidia-drivers kernel-open -tools

