net-analyzer/goaccess geoip geoipv2 getline
app-admin/cockpit -networkmanager
app-metrics/pcp nginx mysql json
www-servers/nginx nginx_modules_http_realip nginx_modules_http_stub_status nginx_modules_http_auth_request nginx_modules_stream_ssl_preread
www-apps/nextcloud redis mysql -postgres -sqlite
dev-lang/php pdo ctype curl gd iconv json filter xml zlib zip opcache intl pcntl unicode xmlwriter xmlreader truetype mysql mysqli exif gmp sodium sysvipc
