llvm-runtimes/openmp abi_x86_32
dev-libs/icu abi_x86_32
media-libs/fontconfig abi_x86_32
sys-libs/libudev-compat abi_x86_32
x11-libs/libdrm abi_x86_32
media-libs/libpulse abi_x86_32
x11-drivers/nvidia-drivers abi_x86_32
media-libs/libglvnd abi_x86_32
x11-libs/libX11 abi_x86_32
x11-libs/libXext abi_x86_32
gui-libs/egl-gbm abi_x86_32
gui-libs/egl-wayland abi_x86_32
gui-libs/egl-wayland2 abi_x86_32
gui-libs/egl-x11 abi_x86_32
media-libs/mesa abi_x86_32
x11-libs/libxcb abi_x86_32
x11-libs/libXau abi_x86_32
x11-libs/libXdmcp abi_x86_32
dev-libs/expat abi_x86_32
dev-util/spirv-tools abi_x86_32
sys-apps/lm-sensors abi_x86_32
media-libs/libva abi_x86_32
dev-libs/wayland abi_x86_32
x11-libs/libxshmfence abi_x86_32
x11-libs/libXxf86vm abi_x86_32
x11-libs/libXfixes abi_x86_32
x11-libs/xcb-util-keysyms abi_x86_32
x11-libs/libXrandr abi_x86_32
x11-libs/libXrender abi_x86_32
media-libs/libsndfile abi_x86_32
net-libs/libasyncns abi_x86_32
sys-apps/dbus abi_x86_32
dev-libs/glib abi_x86_32
dev-libs/libpcre2 abi_x86_32
sys-apps/util-linux abi_x86_32
media-libs/flac abi_x86_32
media-libs/libogg abi_x86_32
media-libs/libvorbis abi_x86_32
media-libs/opus abi_x86_32
media-sound/lame abi_x86_32
media-sound/mpg123 abi_x86_32
media-sound/mpg123-base abi_x86_32
media-libs/freetype abi_x86_32
app-arch/bzip2 abi_x86_32
media-libs/libpng abi_x86_32
media-libs/harfbuzz abi_x86_32
x11-libs/cairo abi_x86_32
media-gfx/graphite2 abi_x86_32
x11-libs/pixman abi_x86_32
virtual/libintl abi_x86_32
virtual/libudev abi_x86_32
sys-apps/systemd abi_x86_32
sys-libs/pam abi_x86_32
sys-libs/gdbm abi_x86_32
sys-libs/readline abi_x86_32
virtual/libiconv abi_x86_32
virtual/libelf abi_x86_32
dev-libs/elfutils abi_x86_32
virtual/opengl abi_x86_32
media-libs/vulkan-loader abi_x86_32
media-libs/vulkan-layers abi_x86_32
dev-util/glslang abi_x86_32
dev-util/vulkan-utility-libraries abi_x86_32
media-libs/libdisplay-info abi_x86_32
x11-libs/libXres abi_x86_32
x11-libs/xcb-util-wm abi_x86_32
dev-libs/lzo abi_x86_32
