gnome-base/gdm -X
gnome-base/nautilus -previewer
media-video/pipewire bluetooth extra -ffmpeg libcamera modemmanager pipewire-alsa sound-server
net-misc/networkmanager -ppp -wext
app-admin/conky bundled-toluapp iostats lua-rsvg truetype
sys-auth/polkit -gtk
gnome-extra/gnome-software -firmware
app-crypt/pinentry -gtk
media-plugins/gst-plugins-meta ffmpeg taglib
gnome-base/gnome -classic extras
net-libs/nodejs npm
media-libs/libcamera -sdl
gnome-base/gvfs onedrive
dev-libs/libdbusmenu -gtk gtk3
gnome-extra/evolution-data-server -oauth-gtk3
app-crypt/gcr gtk
gnome-base/gnome-control-center -X
media-libs/glycin vala
media-fonts/noto -extra
media-fonts/fonts-meta -emoji
net-libs/gnome-online-accounts ms365
net-libs/ngtcp2 gnutls
sys-libs/zlib minizip
sys-apps/systemd boot cryptsetup ukify
sys-kernel/installkernel systemd-boot uki ukify dracut
sys-kernel/gentoo-kernel -debug
x11-drivers/nvidia-drivers kernel-open -tools
sys-apps/kmod pkcs7
sys-kernel/linux-firmware compress-zstd -initramfs savedconfig
app-admin/sudo -sendmail
app-crypt/certbot certbot-nginx
sys-firmware/intel-microcode hostonly
gnome-base/gnome -extras
gui-libs/gtk -vulkan

app-misc/mime-types nginx

sys-auth/seatd builtin server
gui-wm/gamescope libei
net-print/cups -X -acl -dbus -pam -systemd -usb

games-util/steam-launcher vulkan
app-office/libreoffice base googledrive java pdfimport -vulkan
media-libs/libsdl2 kms
dev-qt/qtbase gui
media-gfx/loupe -X
sys-devel/gcc lto
media-gfx/gimp bash-completion heif openexr vector-icons xpm
app-admin/logrotate -cron
